"""Writes a preset theme file from the five colors that describe it.

This is Palette.Build in Python, and it has to stay that way. A preset is a file of ten
finished brushes while a saved theme is five colors run through the C# generator - so if the
two disagree, duplicating a preset quietly produces something slightly different from the
preset it came from. Everything here mirrors src/DejaVu.App/Palette.cs exactly: the same lightness
steps, the same text ceilings, the same rounding.
"""
import io, os

PANE_STEPS = [("Hover", 5.1), ("Line", 9.4)]
TEXT_L, TEXTDIM_L = 91.0, 62.7
TEXT_S, TEXTDIM_S = 12.0, 16.0


def to_hsl(hex_value):
    v = hex_value.lstrip("#")
    r, g, b = (int(v[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    hi, lo = max(r, g, b), min(r, g, b)
    span = hi - lo
    lightness = (hi + lo) / 2

    if span < 1e-9:
        return 0.0, 0.0, lightness * 100

    saturation = span / (2 - hi - lo) if lightness > 0.5 else span / (hi + lo)
    hue = ((g - b) / span % 6 if hi == r else
           (b - r) / span + 2 if hi == g else
           (r - g) / span + 4)
    return (hue * 60 + 360) % 360, saturation * 100, lightness * 100


def from_hsl(hue, saturation, lightness):
    hue = (hue % 360 + 360) % 360
    s = min(max(saturation, 0), 100) / 100.0
    l = min(max(lightness, 0), 100) / 100.0

    c = (1 - abs(2 * l - 1)) * s
    x = c * (1 - abs(hue / 60 % 2 - 1))
    m = l - c / 2
    r, g, b = [(c, x, 0), (x, c, 0), (0, c, x),
               (0, x, c), (x, 0, c), (c, 0, x)][int(hue // 60) % 6]
    return "#%02X%02X%02X" % tuple(
        min(max(round((v + m) * 255), 0), 255) for v in (r, g, b))


def build(shell, pane, accent, highlight, live):
    _, _, shell_l = to_hsl(shell)
    pane_h, pane_s, pane_l = to_hsl(pane)
    shell_h, shell_s, _ = to_hsl(shell)

    dark = shell_l < 50
    direction = 1 if dark else -1

    out = [("Background", shell), ("Surface", pane)]
    out += [(key, from_hsl(pane_h, pane_s, pane_l + step * direction))
            for key, step in PANE_STEPS]
    out += [
        ("Text", from_hsl(shell_h, min(shell_s, TEXT_S),
                          TEXT_L if dark else 100 - TEXT_L)),
        ("TextDim", from_hsl(shell_h, min(shell_s, TEXTDIM_S),
                             TEXTDIM_L if dark else 100 - TEXTDIM_L)),
        ("Accent", accent),
        ("AccentMuted", from_hsl(to_hsl(accent)[0], 45, 26 if dark else 78)),
        ("Highlight", highlight),
        ("Live", live),
    ]
    return dict(out)


def write(path, title, blurb, colors):
    c = build(**colors)
    xaml = """<!--
  %s - %s

  Generated by scratchpad/makepreset.py from the five colors a theme is made of:
  Shell %s, Pane %s, Accent %s, Highlight %s, Live %s.
  Everything else here is derived from those, by the same arithmetic Palette.Build uses -
  so duplicating this preset in the editor reproduces it exactly rather than approximately.
-->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

  <!-- Shell and panes -->
  <SolidColorBrush x:Key="Background" Color="%s" />
  <SolidColorBrush x:Key="Surface" Color="%s" />
  <SolidColorBrush x:Key="Hover" Color="%s" />
  <SolidColorBrush x:Key="Line" Color="%s" />

  <SolidColorBrush x:Key="Text" Color="%s" />
  <SolidColorBrush x:Key="TextDim" Color="%s" />

  <!-- Accent -->
  <SolidColorBrush x:Key="Accent" Color="%s" />
  <SolidColorBrush x:Key="AccentMuted" Color="%s" />

  <!-- Selected, and pressed -->
  <SolidColorBrush x:Key="Highlight" Color="%s" />
  <SolidColorBrush x:Key="Live" Color="%s" />

</ResourceDictionary>
""" % (title, blurb,
       colors["shell"], colors["pane"], colors["accent"],
       colors["highlight"], colors["live"],
       c["Background"], c["Surface"], c["Hover"], c["Line"],
       c["Text"], c["TextDim"], c["Accent"], c["AccentMuted"],
       c["Highlight"], c["Live"])

    io.open(path, "w", encoding="utf-8", newline="\r\n").write(xaml)
    return c


# Two levels up from tools/theme-gen, so this keeps working wherever the tree is
# checked out. The hard-coded path it replaced had been wrong since the repository
# was restructured, and nothing said so until a regeneration wrote nowhere.
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "src", "DejaVu.App", "Themes")

# Every preset, by the five colors that describe it. Regenerated from here rather than
# hand-maintained, so a preset file is always exactly what the editor would produce from the
# same five colors - which is what makes Duplicate reproduce a preset instead of approximating
# it. Change a lightness step in Palette.cs, change it here, and re-run.
PRESETS = [
    ("Dark", "Dark",
     "the shipped palette. A faintly blue dark rather than a neutral one, and the reference "
     "every other theme is measured against",
     dict(shell="#1B1D21", pane="#24272C", accent="#4C8DFF",
          highlight="#3DD68C", live="#8EE7BC")),

    ("Nightshade", "Nightshade",
     "built on #9000AC. Purple the whole way through, with the orange highlight that started "
     "this conversation marking whatever is being edited",
     dict(shell="#231726", pane="#2F1E32", accent="#9000AC",
          highlight="#FF8200", live="#FFB66B")),

    ("Ember", "Ember",
     "built on #FF8200. Warm the whole way through - the grays carry the accent's hue, so the "
     "shell reads as warm rather than as gray with an orange edge",
     dict(shell="#251E17", pane="#31281F", accent="#FF8200",
          highlight="#4CC9F0", live="#97E0F6")),

    ("Abyss", "Abyss",
     "deep teal shell, cyan accent. Cool the other way from the default blue",
     dict(shell="#162326", pane="#1E2E32", accent="#3CD3E7",
          highlight="#FFB13B", live="#FFD28D")),

    ("Graphite", "Graphite",
     "no tint at all - the shell is neutral gray and the violet accent is the only color on "
     "the window. The control case for how far tinting is worth taking",
     dict(shell="#1E1E1E", pane="#282828", accent="#9E77F8",
          highlight="#3DD68C", live="#8EE7BC")),

    ("GoVols", "Go Vols",
     "the University of Tennessee's colors. "
     "Tennessee orange on smokey gray, with white marking what is being edited and black "
     "flashing under a pressed key",
     dict(shell="#3A3A3A", pane="#4B4B4B", accent="#FF8200",
          highlight="#FFFFFF", live="#000000")),
]

for file_name, title, blurb, colors in PRESETS:
    built = write(os.path.join(OUT, file_name + ".xaml"), title, blurb, colors)
    print("%-11s %s" % (title, "  ".join(
        built[k] for k in ("Background", "Surface", "Hover", "Line",
                           "Text", "TextDim", "AccentMuted"))))
